source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Project Civ' do
	pod 'GoogleMaps'
    pod 'Alamofire', '~> 4.3'
    pod 'IGListKit', '~> 2.0.0'
    pod 'Eureka', '~> 2.0'
    pod 'YLProgressBar', '~> 3.10.1'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
end